site_name: Research Notes
theme:
  name: material

nav:
  - Home: index.md
  - Notes:
      - Template: notes/note-template.md
      - Example: examples/example-note.md
  - sample: notes/sample.md
  - sample2: notes/sample2.md
